apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-http
  namespace: dev
spec:
  rules:
    - host: 127.0.0.1
      http:
        paths:
          - path: /douyin/user
            backend:
              serviceName: userinfo-demo
              servicePort: 80
