apiVersion: v1
kind: Service
metadata:
  labels:
    app: userinfo-demo
  name: userinfo-demo
  namespace: userinfo-demo
spec:
  ports:
    - port: 8888
      protocol: TCP
      targetPort: 8888
  selector:
    app: userinfo-demo
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: userinfo-demo
  name: userinfo-demo
  namespace: userinfo-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: userinfo-demo
  template:
    metadata:
      labels:
        app: userinfo-demo
    spec:
      containers:
        - name: userinfo-demo-api
          image: douyin/userinfo-demo-api:nightly
          imagePullPolicy: Never
          ports:
            - containerPort: 8888
        - name: userinfo-demo-rpc
          image: douyin/userinfo-demo-rpc:nightly
          imagePullPolicy: Never
          ports:
            - containerPort: 8080