apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: comment
  name: comment
  namespace: comment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: comment
  template:
    metadata:
      labels:
        app: comment
    spec:
      containers:
        - name: comment
          image: douyin/comment:nightly
          imagePullPolicy: Never
