apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mq
  name: mq
  namespace: mq
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mq
  template:
    metadata:
      labels:
        app: mq
    spec:
      containers:
        - name: mq
          image: douyin/mq:nightly
          imagePullPolicy: Never
